module.exports = {
  CONNECT: 'connection',
  DISCONNECT: 'disconnect',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_READ: 'MESSAGE_READ',
  NEW_NOTIFICATION: 'NEW_NOTIFICATION',
  COMPLAINT_UPDATED: 'COMPLAINT_UPDATED',
  COMPLAINT_ASSIGNED: 'COMPLAINT_ASSIGNED',
  DASHBOARD_REFRESH: 'DASHBOARD_REFRESH',
  USER_ONLINE: 'USER_ONLINE',
  USER_OFFLINE: 'USER_OFFLINE',
};
